# Generated by Django 4.1.7 on 2023-03-03 23:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to="profiles"),
            preserve_default=False,
        ),
    ]
